name: PhantomCompatChat
author: RoboMWM
#website: https://www.spigotmc.org/resources/dimension-teleporter.14807/
version: ${project.version}
main: me.robomwm.PhantomCompatChat.Main
commands:
   tell:
      description: Teleport to a dimension or loaded world.
      usage: "\xa7cUsage: /tell <player> <private message ...>"
      permission: phantomcompatchat.tell
permissions:
    phantomcompatchat.*:
        description: Grants ALL THE ONE THING
        children:
            phantomcompatchat.tell: true
    phantomcompatchat.tell:
        description: Permission to /tell
        default: true